### ISSUE TITLE
node-gyp rebuild step hangs

### ISSUE THREAD

**Issue by lukelex** [mgutz/execSync#16]
Hi, I've been trying to install this lib for the past two days and it hangs forever after reaching the _node-gyp rebuild_ step.

```
➜ assetline $ npm install execSync
npm WARN package.json execSync@1.0.1-pre No repository field.
npm http GET https://registry.npmjs.org/execSync
npm http 304 https://registry.npmjs.org/execSync
npm http GET https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/temp

> execSync@1.0.1-pre install /Users/Lukas/projects/codelogic/assetline/node_modules/execSync
> node-gyp rebuild

```

**Comment by rockallite** [comment]
I resolve the hang problem of ```node-gyp rebuild``` by the [following methods](http://gangmax.me/blog/2013/05/13/resolve-npm-update-node-gyp-hung-problem/):

    npm install -g node-gyp

Then re-run the process with ```npm update```.

**Comment by phatmann** [comment]
@foxinni thanks this trick worked perfectly.
