### ISSUE TITLE
Problems with grunt-favicons and win32

### ISSUE THREAD

**Issue by maraisr** [mgutz/execSync#24]
There is a problem running grunt-favions, the output states that execSync isnt compatible with the installed node, which is grunt-favicons. 

The exact error is:
Loading "favicons.js" tasks...ERROR
Error: execSync incompatible with installed nodejs

**Comment by vvelar** [comment]
Did author check his 'product' on windows at all? @IanMercer solution did not worked for me :(
Windows 7.1

**Comment by novice3030** [comment]
I'm also still fighting this the fix doesn't work for me

**Comment by JarekCzyz** [comment]
@IanMercer  thanks! It works for me :+1:

**Comment by maraisr** [comment]
I no longer have this issues - must have been resolved.
