### ISSUE TITLE
Fails to build on node 0.11.16

### ISSUE THREAD

**Issue by kriswill** [mgutz/execSync#36]
Causes downstream packages to fail to install on latest node 0.11.16 see https://github.com/LevelbossMike/ember-deploy/issues/31

**Comment by mgutz** [comment]
I think 0.11 has execSync

**Comment by kriswill** [comment]
You are correct!  

```js
var exec = require('execSync');
```
vs.
```js
var exec = require('child_process').execFileSync
```
How can I prevent a node module from installing in package.json if node >= 11?

**Comment by mgutz** [comment]
Something like this should work.

```js
if (process.version.IndexOf('v0.11') === 0) {
   // require v0.11 here
} else {
  // must be older
}
```

**Comment by kriswill** [comment]
I ended up with:

```js
var commandResult;
if (require('child_process').execSync) {
  commandResult = require('child_process').execSync("git rev-parse HEAD");
} else {
  commandResult = require('execSync').exec("git rev-parse HEAD").stdout;
}
```

The interface for child_process.execSync returns buffer or string, vs object for your lib.
